version: 2.1
orbs:
  node: circleci/node@3.0.0
  coveralls: coveralls/coveralls@1.0.6
workflows:
  node-tests:
    jobs:
      - node/test
      - run:
          name: Test with coverage
          command: npm test --coverage
      - coveralls/upload

